### ISSUE TITLE
Adding hystrix - Logs stacktrace error

### ISSUE THREAD

**Issue by davsclaus** [nicolaferraro/camel-workshop#14]
When we add hystrix, then we call a sub route via direct
https://github.com/nicolaferraro/camel-workshop/blob/master/doc/circuit-breaker.md#adding-a-circuit-breaker

And this causes Camel to by default to log an ERROR as the sub-route failed
```
2018-06-07 14:00:52.825 ERROR 62672 --- [   XNIO-3 I/O-1] o.a.camel.processor.DefaultErrorHandler  : Failed delivery for (MessageId: ID-davsclaus-pro-local-1528372823733-0-40 on ExchangeId: ID-davsclaus-pro-local-1528372823733-0-39). Exhausted after delivery attempt: 1 caught: java.net.ConnectException: Connection refused


java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_131]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_131]
	at org.xnio.nio.WorkerThread$ConnectHandle.handleReady(WorkerThread.java:321) ~[xnio-nio-3.3.8.Final.jar:3.3.8.Final]
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:561) ~[xnio-nio-3.3.8.Final.jar:3.3.8.Final]
```

I wonder if we should get this removed, but this would with this version of Camel require to either
- turn off error handling in the sub route via `errorHandler(noErrorHandler)`
- or do not use sub route via direct, but have it all inside the hystrix block.

And we should consider if this default is a good mode in Apache Camel. Maybe for Camel 3.0 we revisit the error handler, as it may make sense to not have error handling enabled when inside hystrix, doTry etc - also for sub routes.

**Comment by nicolaferraro** [comment]
I can try to change the guide. Instead of wrapping a subroute, I can add hystrix directly to the existing route so that the exception is not printed.

Yes, for Camel 3 we should revisit hystrix. Also with something like Istio as service mesh, a try/catch should be sufficient to handle fallback (and the exception-printing behavior should be the same even if using subroutes).

**Comment by nicolaferraro** [comment]
done
